# Generated by Django 5.2.6 on 2025-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_appointment_patient_patientvisit_prescription_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('doctor', 'appointment_date', 'appointment_time'), name='uniq_active_appointment_per_slot'),
        ),
    ]
