# Generated by Django 5.2.6 on 2025-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
